Homepage
abredi/newsweek-clone pull request #1
Opened 2020-06-17 15:17 UTC by abredi

- added home page for the newsweek.com clone
- responsive with mobile first design
- used [bootstrap](https://getbootstrap.com/) css framework
- HTML and CSS

2020-06-17 18:34 UTC, christianotieno commented
## Pull Request under review by Christian Otieno (TSE)

2020-06-17 18:54 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @abredi   :wave:
-
Good job with the first attempt! :tada:  We, however, do have some few changes to carry out before we proceed (see review comment).
##

- For this project, we have to make sure nothing is messed up. The clone and the source page have to appear strikingly similar. Kindly compare between the two and work on the differences 👇 .

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/abredi/newsweek-clone/homepage/index.html)|
|:---:|:---:|
|![source](https://user-images.githubusercontent.com/22345961/84936690-5185a800-b0e3-11ea-94f2-5315f18979fb.png)|![clone](https://user-images.githubusercontent.com/22345961/84936709-58acb600-b0e3-11ea-8df0-0c27d5374f58.png)|

- Currently, the clone has a grey navbar spanning the entire screen width. Fix that.
-  The far-right contents are out of place kindly work on that as well.
- Improve on the visuals of the page by adding actual images as well.

See the differences in the footer section and work on them as well.

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/abredi/newsweek-clone/homepage/index.html)|
|:---:|:---:|
|![footer](https://user-images.githubusercontent.com/22345961/84937040-d5d82b00-b0e3-11ea-8a6d-acb668ef9ef1.png)|![footer-clone](https://user-images.githubusercontent.com/22345961/84937050-da9cdf00-b0e3-11ea-8ff6-7ca6b5e77a16.png)|

For the project to get approved make sure it adheres to the following: 👇 
- [ ] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] Basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright).
- [ ] Validate the HTML markup with this [validator](https://validator.w3.org/nu/#textarea). ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright).

- [ ] Linter is enabled for this project and the stylesheets are passing the checks.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-20 00:03 UTC, elmejdki requested changes
# Great job so far @abredi :clap: your project looks soo much like the original :tophat:, but in order to approve your project you still have some minor changes to make.
### status: require changes :recycle: 

- please fix the overlapping between the text and the image in the subscribe section:
![image](https://user-images.githubusercontent.com/34653764/85186550-a109d680-b291-11ea-91b9-505b5be6c740.png)

### you have to fix only that issue and you are good to go, please fix it before requesting another code review
### Happy Coding :tophat:

2020-06-20 00:33 UTC, abredi commented
@elmejdki Thanks man for your humble words. Its looks good in by my side, could you tell me the screen resolution that produces the issue?
<img width="771" alt="Screen Shot 2020-06-20 at 3 31 28 AM" src="https://user-images.githubusercontent.com/38358081/85187195-8b52dc00-b2a6-11ea-9fd2-2eb987bdee1a.png">

2020-06-20 01:14 UTC, voscarmv approved these changes
# Impressive work! 🖥️ 👀 ✨ 
## It's a ✔️ YES ✔️ for me! Congrats: Project approved 👏  👏  👏 

Please read the code comments for some extra advice though!

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-06-20 01:14 UTC, voscarmv commented on assets/css/main.css
> +}
**[OPTIONAL]** The images appear stretched on certain screen widths:

![image](https://user-images.githubusercontent.com/2739245/85187894-de0da300-b268-11ea-8147-1fa321aaa77b.png)

You could solve this by using CSS properties `background-size: cover` and `bakcground-position: 50% 50%` instead of simply `width` and `height`. Check out [this](https://stackoverflow.com/questions/11757537/css-image-size-how-to-fill-not-stretch) stack overflow question for reference.

2020-06-20 01:33 UTC, abredi commented on assets/css/main.css
> +}
Okay, I will fix that. Thanks @voscarmv

2020-06-20 16:12 UTC, merged

2020-06-21 15:47 UTC, abredi commented on assets/css/main.css
> +}
fixed: Its already fixed now. I appreciate your reviews.